version: '3.8'
services:
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile
    ports:
      - "5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=PochtaTest
    volumes:
      - "db-data:/var/lib/postgresql/data"
  
  
  app:
    build:
      context: services/app
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/PochtaTest
      - JS_URL=http://localhost
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - WEATHER_APIKEY=caa82bb2456d41e8007d9baf251e9ab6
    image: 'pochta-app'
    ports:
      - "8080:8080"
    depends_on:
      - postgres
        
volumes:
   db-data: